# Generated by Django 5.0.3 on 2024-03-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='size',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
